import type { CheckDefinition, Finding } from '../../types.js';

function looksAutoGenerated(nameWithoutExt: string, patterns: RegExp[]): boolean {
  return patterns.some((pattern) => pattern.test(nameWithoutExt));
}

/**
 * Flags images served from opaque, auto-generated-looking paths (e.g. a media
 * library hash like "/media/asdifojasidng.webp") instead of a descriptive,
 * keyword-relevant filename (e.g. "/media/red-running-shoes.webp") — descriptive
 * filenames are a real (if minor) image-search ranking signal. This is a
 * heuristic on the filename shape, not certainty, so it warns rather than fails.
 */
export const imageFilenameCheck: CheckDefinition = {
  id: 'seo.image-filename',
  name: 'Descriptive image filenames',
  category: 'seo',
  run: ({ extracted, config }) => {
    const findings: Finding[] = [];

    for (const image of extracted.images) {
      const url = image.resolvedSrc ?? image.src;
      if (!url || url.startsWith('data:')) continue;

      let pathname: string;
      try {
        pathname = new URL(url).pathname;
      } catch {
        pathname = url;
      }
      const filename = pathname.split('/').pop() ?? '';
      const nameWithoutExt = filename.replace(/\.[a-z0-9]+$/i, '');
      if (!nameWithoutExt) continue;

      if (looksAutoGenerated(nameWithoutExt, config.thresholds.hashLikeFilenamePatterns)) {
        findings.push({
          checkId: 'seo.image-filename',
          status: 'warn',
          detail: `Image uses a non-descriptive, likely auto-generated filename ("${filename}") instead of a readable, keyword-relevant name: ${image.src}`,
          data: { src: image.src, filename },
        });
      }
    }

    if (findings.length === 0) {
      return {
        checkId: 'seo.image-filename',
        status: 'pass',
        detail:
          extracted.images.length > 0
            ? `All ${extracted.images.length} image filename(s) look descriptive.`
            : 'No images found on the page.',
      };
    }
    return findings;
  },
};
