ALTER TABLE `AuditRun`
  ADD COLUMN `staleContentCount` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `nearDuplicateGroups` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `headingViolations` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `mixedContentPages` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `canonicalSelfRate` DOUBLE NULL,
  ADD COLUMN `canonicalChains` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `canonicalNon200` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `crawlWasteUrls` INTEGER NOT NULL DEFAULT 0;
